version: "2.3"

services:
  web:
    image: desycopo/aji-gcn:flask
    runtime: nvidia
    ports:
      - "5000:5000"
    volumes:
      - ../:/mnt/
    working_dir: /mnt/serving-side/
    links:
      - db
    command: python -u app.py
  db:
    image: mongo:4.2-bionic