# command line: /mnt/serving-side/app.py

base_lr: 0.01
batch_size: 256
config: config/test.yaml
debug: false
device: 0
eval_interval: 5
feeder: feeder.feeder_kinetics.Feeder_kinetics
id_process: id_y
ignore_weights: []
index_data: test_X
log_interval: 100
model: net.st_gcn.Model
model_args:
    dropout: 0.5
    edge_importance_weighting: true
    graph_args:
        layout: openpose
        strategy: spatial
    in_channels: 3
    num_class: 6
nesterov: true
num_epoch: 80
num_worker: 4
optimizer: SGD
pavi_log: false
phase: test
print_log: false
save_interval: 10
save_log: true
save_result: false
show_topk:
- 1
- 5
start_epoch: 0
step: []
test_batch_size: 2
test_feeder_args:
    data_path: static/npy_data/02-12-2020_06:12:54.827.npy
train_feeder_args: {}
use_gpu: true
weight_decay: 0.0001
weights: ./config/best_tested.pt
work_dir: ./work_dir/tmp
